### ISSUE TITLE
can i kick someone from room?

### ISSUE THREAD

**Issue by enty8080** [WolkoDav/TCP-Chat#1]

**Comment by enty8080** [comment]
@ikrivosheev Могу ли я кикнуть кого-то из чата?

**Comment by ikrivosheev** [comment]
Здравствуйте, нет, т.к. нету системы ролей.

**Comment by enty8080** [comment]
Жаль, но я могу попробовать добавить если это возможно

**Comment by ikrivosheev** [comment]
Если есть необходимость, то я не вижу проблем.

**Comment by enty8080** [comment]
@ikrivosheev, а можете подсказать, что надо поменять чтобы отключить члена комнаты (пока без системы ролей)? Просто я никак не могу найти в вашем коде часть в которой идет обработка пользователей. Спасибо)

**Comment by ikrivosheev** [comment]
В `Message` есть два поля: `command: str`, `kwargs: dict`. В `kwargs` передаётся пользователь, который отправил запрос. В `Storage` вся эта информация и храниться.

Сам код сервера: https://github.com/ikrivosheev/TCP-Chat/blob/master/server.py
Код клиента: https://github.com/ikrivosheev/TCP-Chat/blob/master/client.py

**Comment by enty8080** [comment]
Спасибо! Но к сожалению у меня не получилось(
